/*
 * Copyright 2020 Google LLC.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

object Libs {
    const val ACTIVITY_KTX = "androidx.activity:activity-ktx"
    const val ANDROIDX_HILT_COMPILER = "androidx.hilt:hilt-compiler"
    const val APPCOMPAT = "androidx.appcompat:appcompat"
    const val ARCH_TESTING = "androidx.arch.core:core-testing"
    const val ARCORE = "com.google.ar:core"
    const val ADMOB = "com.google.android.gms:play-services-ads"
    const val AMPLIFY_CORE = "com.amplifyframework:core"
    const val AMPLIFY_STORAGE = "com.amplifyframework:aws-storage-s3"
    const val AMPLIFY_AUTH = "com.amplifyframework:aws-auth-cognito"
    const val BENCHMARK = "androidx.benchmark:benchmark-junit4"
    const val BROWSER = "androidx.browser:browser"
    const val CARDVIEW = "androidx.cardview:cardview"
    const val CONSTRAINT_LAYOUT = "androidx.constraintlayout:constraintlayout"
    const val CORE_KTX = "androidx.core:core-ktx"
    const val COROUTINES = "org.jetbrains.kotlinx:kotlinx-coroutines-core"
    const val COROUTINES_TEST = "org.jetbrains.kotlinx:kotlinx-coroutines-test"
    const val CIRCLE_IMAGE_VIEW = "de.hdodenhof:circleimageview"
    const val DRAWER_LAYOUT = "androidx.drawerlayout:drawerlayout"
    const val ESPRESSO_CONTRIB = "androidx.test.espresso:espresso-contrib"
    const val ESPRESSO_CORE = "androidx.test.espresso:espresso-core"
    const val EXT_JUNIT = "androidx.test.ext:junit"
    const val FACEBOOK_ADS = "com.google.ads.mediation:facebook"
    const val FIREBASE_ANALYTICS = "com.google.firebase:firebase-analytics-ktx"
    const val FIREBASE_CRASHLYTICS = "com.google.firebase:firebase-crashlytics-ktx"
    const val FIREBASE_AUTH = "com.google.firebase:firebase-auth-ktx"
    const val FIREBASE_CONFIG = "com.google.firebase:firebase-config-ktx"
    const val FIREBASE_FIRESTORE = "com.google.firebase:firebase-firestore-ktx"
    const val FIREBASE_FUNCTIONS = "com.google.firebase:firebase-functions-ktx"
    const val FIREBASE_MESSAGING = "com.google.firebase:firebase-messaging-ktx"
    const val FIREBASE_IN_APP_MESSAGING = "com.google.firebase:firebase-inappmessaging-ktx"
    const val FIREBASE_IN_APP_MESSAGING_DISPLAY = "com.google.firebase:firebase-inappmessaging-display-ktx"
    const val FIREBASE_UI_AUTH = "com.firebaseui:firebase-ui-auth"
    const val FLEXBOX = "com.google.android:flexbox"
    const val FRAGMENT_KTX = "androidx.fragment:fragment-ktx"
    const val GLIDE = "com.github.bumptech.glide:glide"
    const val GLIDE_COMPILER = "com.github.bumptech.glide:compiler"
    const val GLIDE_SVG = "com.github.qoqa:glide-svg"
    const val GOOGLE_BASEMENT = "com.google.android.gms:play-services-basement"
    const val GOOGLE_MAP_UTILS = "com.google.maps.android:android-maps-utils"
    const val GOOGLE_PLAY_SERVICES_MAPS = "com.google.android.gms:play-services-maps"
    const val GOOGLE_PLAY_SERVICES_VISION = "com.google.android.gms:play-services-vision"
    const val GSON = "com.google.code.gson:gson"
    const val HAMCREST = "org.hamcrest:hamcrest-library"
    const val HILT_ANDROID = "com.google.dagger:hilt-android"
    const val HILT_ANDROIDX_WORK = "androidx.hilt:hilt-work"
    const val HILT_VIEWMODEL = "androidx.hilt:hilt-lifecycle-viewmodel"
    const val HILT_COMPILER = "com.google.dagger:hilt-android-compiler"
    const val HILT_TESTING = "com.google.dagger:hilt-android-testing"
    const val HTML_TEXT_VIEW = "org.sufficientlysecure:html-textview"
    const val INK_PAGE_INDICATOR = "com.pacioianu.david:ink-page-indicator"
    const val IMAGE_PICKER = "com.github.dhaval2404:imagepicker"
    const val INLINE_ACTIVITY_RESULT = "com.github.florent37:inline-activity-result-kotlin"
    const val JUNIT = "junit:junit"
    const val KOTLIN_STDLIB = "org.jetbrains.kotlin:kotlin-stdlib"
    const val LIFECYCLE_COMPILER = "androidx.lifecycle:lifecycle-compiler"
    const val LIFECYCLE_LIVE_DATA_KTX = "androidx.lifecycle:lifecycle-livedata-ktx"
    const val LIFECYCLE_VIEW_MODEL_KTX = "androidx.lifecycle:lifecycle-viewmodel-ktx"
    const val LOTTIE = "com.airbnb.android:lottie"
    const val MATERIAL = "com.google.android.material:material"
    const val MOCKITO_CORE = "org.mockito:mockito-core"
    const val MOCKITO_KOTLIN = "com.nhaarman:mockito-kotlin"
    const val MP_ANDROID_CHART = "com.github.PhilJay:MPAndroidChart"
    const val NAVIGATION_FRAGMENT_KTX = "androidx.navigation:navigation-fragment-ktx"
    const val NAVIGATION_UI_KTX = "androidx.navigation:navigation-ui-ktx"
    const val OKHTTP = "com.squareup.okhttp3:okhttp"
    const val OKHTTP_LOGGING_INTERCEPTOR = "com.squareup.okhttp3:logging-interceptor"
    const val OKIO = "com.squareup.okio:okio"
    const val RETROFIT = "com.squareup.retrofit2:retrofit"
    const val RETROFIT_GSON_CONVERTER = "com.squareup.retrofit2:converter-gson"
    const val RETROFIT_RXJAVA_ADAPTER = "com.squareup.retrofit2:adapter-rxjava2"
    const val ROOM_COMPILER = "androidx.room:room-compiler"
    const val ROOM_KTX = "androidx.room:room-ktx"
    const val ROOM_RUNTIME = "androidx.room:room-runtime"
    const val RULES = "androidx.test:rules"
    const val RUNNER = "androidx.test:runner"
    const val TED_IMAGE_PICKER = "gun0912.ted:tedimagepicker"
    const val THREETENABP = "com.jakewharton.threetenabp:threetenabp"
    const val THREETENBP = "org.threeten:threetenbp"
    const val TIMBER = "com.jakewharton.timber:timber"
    const val VIEWPAGER2 = "androidx.viewpager2:viewpager2"
    const val WORK_RUNTIME = "androidx.work:work-runtime-ktx"
    const val WORK_GCM = "androidx.work:work-gcm"
    const val WORK_RXJAVA = "androidx.work:work-rxjava2"
    const val YOUTUBE = "kr.co.prnd:youtube-player-view"
}
